# swagger: https://api-docs.firefly-iii.org/

### Ping info method
GET {{host}}api/v1/about
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}api/v1/transactions
Authorization: Bearer {{token}}
Content-Type: application/json
accept: application/vnd.api+json

{
  "transactions": [
    {
      "source_name": "Tinkoff Карта",
      "destination_id": 10,
      "type": "withdrawal",
      "date": "2021-10-03T12:46:47+01:00",
      "amount": "123.45",
      "description": "Vegetables"
    }
  ]
}
